name: Deploy to Xserver via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.XSERVER_FTP_SERVER }}
          username: ${{ secrets.XSERVER_FTP_USERNAME }}
          password: ${{ secrets.XSERVER_FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.XSERVER_FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/.vscode*/**
            README.md
